/* Terjemahan EN untuk laporan di Daftar Laporan — dipakai saat lang = "en".
 * Struktur: Record<categoryKey, Record<judul-ID, { t: judul-EN, d: deskripsi-EN }>>.
 */

export const REPORT_EN: Record<string, Record<string, { t: string; d: string }>> = {
  keuangan: {
    "Laba/Rugi (Standar)": { t: "P&L (Standard)", d: "Displays the profit & loss report for the selected period" },
    "Laba/Rugi (Multi Periode)": { t: "P&L (Multi Period)", d: "Displays monthly profit & loss within the selected period range" },
    "Laba/Rugi (Multi Year)": { t: "P&L (Multi Year)", d: "Displays year-end profit & loss for the last 3 years" },
    "Laba/Rugi (Kuartal)": { t: "P&L (Quarterly)", d: "Displays quarterly profit & loss for the selected year" },
    "Laba/Rugi (Perbandingan Periode)": { t: "P&L (Period Comparison)", d: "Displays profit & loss compared to the previous period, with difference shown as percentage" },
    "Laba/Rugi (Perbandingan Anggaran)": { t: "P&L (Budget Comparison)", d: "Displays profit & loss with budget columns, comparison, and percentages" },
    "Neraca (Standar)": { t: "Balance Sheet (Standard)", d: "Displays the standard balance sheet" },
    "Neraca (Multi Periode)": { t: "Balance Sheet (Multi Period)", d: "Displays the balance sheet at month-end within the selected period range" },
    "Neraca (Multi Year)": { t: "Balance Sheet (Multi Year)", d: "Displays the balance sheet at year-end for the last 3 years" },
    "Neraca (Perbandingan Periode)": { t: "Balance Sheet (Period Comparison)", d: "Displays the balance sheet compared to the previous period, with difference shown as percentage" },
    "Neraca (Induk Skontro)": { t: "Balance Sheet (Account Form)", d: "Displays the balance sheet in horizontal (account form) layout" },
    "Arus Kas (Langsung)": { t: "Cash Flow (Direct)", d: "Displays cash inflows and outflows for a specific period" },
    "Arus Kas (Tak Langsung)": { t: "Cash Flow (Indirect)", d: "Displays cash inflows and outflows for a specific period" },
    "Rincian Arus Kas (Tak Langsung)": { t: "Cash Flow Detail (Indirect)", d: "Displays cash flow for a specific period; 3 sections: operating, investing, financing activities" },
    "Proyeksi Kas per Bulan": { t: "Monthly Cash Projection", d: "Displays estimated cash value for the next 5 months" },
    "Proyeksi Ketersediaan Kas": { t: "Cash Availability Projection", d: "Displays a projection chart of cash availability in upcoming periods" },
    "Rincian Gaji Karyawan per Bulan": { t: "Monthly Employee Salary Details", d: "Displays salary and allowance details per employee per month" },
    "Rincian Gaji Karyawan per Tahun": { t: "Yearly Employee Salary Details", d: "Displays salary and allowance details per employee per year" },
    "Porsi Gaji Karyawan": { t: "Employee Salary Portion", d: "Displays the proportion of all employee salaries" },
    "Rasio Keuangan (Per Tahun)": { t: "Financial Ratios (Yearly)", d: "Displays annual ratio information for your company data" },
    "Rasio Keuangan (Per Bulan)": { t: "Financial Ratios (Monthly)", d: "Displays monthly ratio information for your company data" },
  },
  "buku-besar": {
    "Keseluruhan Jurnal": { t: "Entire Journal", d: "Report showing all journals from transactions" },
    "Keseluruhan Jurnal (CSV)": { t: "Entire Journal (CSV)", d: "Download CSV data of the report showing all journals from transactions" },
    "Ringkasan Buku Besar": { t: "General Ledger Summary", d: "General ledger summary report" },
    "Histori Buku Besar": { t: "General Ledger History", d: "General ledger history report" },
    "Histori Buku Besar (CSV)": { t: "General Ledger History (CSV)", d: "Download CSV data of the general ledger history report" },
    "Rincian Buku Besar": { t: "General Ledger Detail", d: "General ledger detail report" },
    "Rincian Buku Besar (CSV)": { t: "General Ledger Detail (CSV)", d: "Download CSV data of the general ledger detail report" },
    "Rincian Jurnal Akun": { t: "Account Journal Details", d: "Report showing journaling process details for each account in the selected period" },
    "Rincian Jurnal Akun (CSV)": { t: "Account Journal Details (CSV)", d: "Download CSV data of journaling process details for each account" },
    "Laba/Rugi Terealisasi": { t: "Realized P&L", d: "Shows profit/loss caused by exchange rate differences between invoices and their payments" },
    "Laba/Rugi Tidak Terealisasi": { t: "Unrealized P&L", d: "Shows unrealized profit/loss from exchange rate differences after the month-end process" },
    "Neraca Percobaan": { t: "Trial Balance", d: "Report showing the changes in account balances" },
    "Daftar Akun Perkiraan": { t: "Chart of Accounts", d: "Report containing the list of accounts" },
    "Jurnal Umum": { t: "General Journal", d: "Report containing the list of general journals" },
    "Pajak Penghasilan Karyawan": { t: "Employee Income Tax", d: "Displays the list of employee income tax values per month" },
  },
  "kas-bank": {
    "Histori Bank": { t: "Bank History", d: "Bank history report" },
    "Transaksi Bank Terekonsiliasi": { t: "Reconciled Bank Transactions", d: "Report of reconciled bank transactions" },
    "Transaksi Bank Belum Terekonsiliasi": { t: "Unreconciled Bank Transactions", d: "Report of unreconciled bank transactions" },
    "Ringkasan Pembayaran per Bank": { t: "Payment Summary per Bank", d: "Payment summary report per bank" },
    "Ringkasan Penerimaan per Bank": { t: "Receipt Summary per Bank", d: "Receipt summary report per bank" },
    "Giro Mundur (Belum Jatuh Tempo)": { t: "Outstanding Checks (Not Due)", d: "Report of checks that have not yet matured" },
    "Arus Kas per Akun": { t: "Cash Flow per Account", d: "Cash flow report detailed per expense/income account" },
    "Rincian Pembayaran per Bank": { t: "Payment Details per Bank", d: "Payment detail report per bank" },
    "Rincian Penerimaan per Bank": { t: "Receipt Details per Bank", d: "Receipt detail report per bank" },
    "Daftar Kas": { t: "Cash & Bank Accounts", d: "Report listing cash and bank accounts" },
    "Rekening Koran": { t: "Bank Statement", d: "Displays bank statement details within a selected period" },
    "Ringkasan Daftar Pembayaran": { t: "Payment List Summary", d: "Report containing the summary of payments" },
    "Ringkasan Daftar Penerimaan": { t: "Receipt List Summary", d: "Report containing the summary of receipts" },
    "Rincian Beban Pembayaran": { t: "Payment Expense Details", d: "Report containing payment expense details" },
    "Rekonsiliasi Bank (Jurnal terhadap Rekening Koran)": { t: "Bank Reconciliation (Journal to Statement)", d: "Bank reconciliation report filtered by journal date" },
    "Rekonsiliasi Bank (Rekening Koran terhadap Jurnal)": { t: "Bank Reconciliation (Statement to Journal)", d: "Bank reconciliation report filtered by statement date" },
    "Daftar Piutang Karyawan": { t: "Employee Receivables", d: "Displays employee loan details" },
    "Angsuran Pinjaman per Karyawan": { t: "Employee Loan Installments", d: "Displays loan installments per employee" },
  },
  piutang: {
    "Faktur Belum Lunas": { t: "Unpaid Invoices", d: "Displays invoices that have not been paid" },
    "Faktur Belum Lunas per Pelanggan": { t: "Unpaid Invoices per Customer", d: "Displays total unpaid invoices per customer" },
    "Umur Piutang": { t: "Receivables Aging", d: "Displays the age of unpaid customer receivables" },
    "Rincian Umur Piutang": { t: "Receivables Aging Detail", d: "Displays the age of unpaid invoice receivables" },
    "Histori Piutang": { t: "Receivables History", d: "Displays detailed customer receivable transactions" },
    "Buku Besar Pembantu Piutang": { t: "Receivables Subsidiary Ledger", d: "Displays invoice, receipt, and return values per customer" },
    "Rincian Buku Besar Pembantu Piutang": { t: "Receivables Subsidiary Ledger Detail", d: "Displays detailed invoice, receipt, and return transactions per customer" },
    "Rata-rata Pembayaran Pelanggan": { t: "Average Customer Payment Days", d: "Displays the average number of days customers pay bills" },
    "Grafik Rata-rata Pembayaran Pelanggan": { t: "Average Customer Payment Days Chart", d: "Displays a chart of average payment days per month" },
    "Grafik Umur Piutang": { t: "Receivables Aging Chart", d: "Displays a chart of unpaid customer receivables aging" },
    "Pernyataan Piutang": { t: "Receivables Statement", d: "Displays detailed receivable statements to customers" },
    "Pembayaran Faktur": { t: "Invoice Payments", d: "Displays the list of invoice payments" },
    "Pembayaran PPh Penjualan": { t: "Sales Income Tax Payments", d: "Displays payments for self-withheld sales income tax" },
    "Penerimaan Penjualan": { t: "Sales Receipts", d: "Displays the list of payments received from customers" },
    "Rincian Penerimaan Penjualan": { t: "Sales Receipt Details", d: "Displays detailed payment receipts from customers" },
    "Sisa Kredit Pelanggan": { t: "Customer Credit Balances", d: "Displays remaining credit (overpayment) per customer" },
    "Limit Piutang Pelanggan": { t: "Customer Receivable Limits", d: "Report of customers with their remaining receivable limit" },
    "Daftar Pelanggan": { t: "Customer List", d: "Report containing the list of customers" },
  },
  penjualan: {
    "Penjualan per Pelanggan": { t: "Sales per Customer", d: "Displays sales value list per customer" },
    "Penjualan per Barang": { t: "Sales per Item", d: "Displays sales value list per item" },
    "Penjualan per Merek": { t: "Sales per Brand", d: "Displays sales value list per brand" },
    "Penjualan per Cabang": { t: "Sales per Branch", d: "Displays sales value list per branch" },
    "Penjualan Barang per Gudang": { t: "Item Sales per Warehouse", d: "Displays item sales values per warehouse" },
    "Penjualan Barang per Cabang": { t: "Item Sales per Branch", d: "Displays item sales values per branch" },
    "Penjualan Barang per Pelanggan": { t: "Item Sales per Customer", d: "Displays item sales values per customer" },
    "Penjualan Pelanggan per Barang": { t: "Customer Sales per Item", d: "Displays customer sales values per item" },
    "Histori Proses Penjualan": { t: "Sales Process History", d: "Displays the sales process chain from quotation to payment" },
    "Rincian Penjualan per Barang": { t: "Sales Details per Item", d: "Displays sales value details per item" },
    "Rincian Penjualan per Pelanggan": { t: "Sales Details per Customer", d: "Displays sales value details per customer" },
    "Retur Penjualan per Barang": { t: "Sales Returns per Item", d: "Displays sales return values per item" },
    "Grafik Penjualan Bulanan": { t: "Monthly Sales Chart", d: "Displays a monthly sales bar chart" },
    "Porsi Penjualan per Barang": { t: "Sales Portion per Item", d: "Displays the portion of sales from items" },
    "Porsi Penjualan per Pelanggan": { t: "Sales Portion per Customer", d: "Displays the portion of sales from customers" },
    "Penawaran per Barang (Belum Proses)": { t: "Quotations per Item (Unprocessed)", d: "Displays unprocessed sales quotation values per item" },
    "Penawaran per Pelanggan (Belum Proses)": { t: "Quotations per Customer (Unprocessed)", d: "Displays unprocessed sales quotation values per customer" },
    "Pesanan per Pelanggan (Belum Proses)": { t: "Orders per Customer (Unprocessed)", d: "Displays unprocessed sales order values per customer" },
  },
  "tenaga-penjual": {
    "Faktur Belum Lunas per Penjual": { t: "Unpaid Invoices per Salesperson", d: "Displays unpaid invoices grouped per salesperson" },
    "Umur Piutang per Penjual": { t: "Receivables Aging per Salesperson", d: "Displays the age of customer receivables per salesperson" },
    "Rincian Umur Piutang per Penjual": { t: "Receivables Aging Detail per Salesperson", d: "Displays receivable aging transaction details per salesperson" },
    "Faktur Penjualan per Penjual": { t: "Sales Invoices per Salesperson", d: "Displays sales invoice list grouped per salesperson" },
    "Penjualan Barang per Penjual": { t: "Item Sales per Salesperson", d: "Displays item sales values per salesperson" },
    "Retur Penjualan per Penjual": { t: "Sales Returns per Salesperson", d: "Displays sales returns grouped per salesperson" },
    "Ringkasan Komisi (Dihitung per Periode)": { t: "Commission Summary (Calculated per Period)", d: "Report of commission values per salesperson, calculated cumulatively per month" },
    "Ringkasan Komisi (Dihitung per Faktur)": { t: "Commission Summary (Calculated per Invoice)", d: "Report of commission values per salesperson, calculated per invoice" },
    "Rincian Komisi (Dihitung per Periode)": { t: "Commission Detail (Calculated per Period)", d: "Report of monthly commission calculation details for salespersons" },
    "Rincian Komisi (Dihitung per Faktur)": { t: "Commission Detail (Calculated per Invoice)", d: "Report of commission calculation details per invoice for salespersons" },
    "Daftar Komisi Penjual": { t: "Salesperson Commission List", d: "Report containing commission calculations for salespersons" },
    "Histori Transaksi per Penjual": { t: "Transaction History per Salesperson", d: "Displays transaction history per salesperson" },
    "Check In per Karyawan": { t: "Check In per Employee", d: "Displays check-in details per employee on selected dates" },
  },
  utang: {
    "Faktur Belum Lunas": { t: "Unpaid Invoices", d: "Displays invoices that have not been paid" },
    "Faktur Belum Lunas per Pemasok": { t: "Unpaid Invoices per Supplier", d: "Displays total unpaid invoices per supplier" },
    "Umur Utang": { t: "Payables Aging", d: "Displays the age of unpaid payables to suppliers" },
    "Rincian Umur Utang": { t: "Payables Aging Detail", d: "Displays the age of unpaid invoice payables" },
    "Histori Utang": { t: "Payables History", d: "Displays detailed supplier payable transactions" },
    "Buku Besar Pembantu Utang": { t: "Payables Subsidiary Ledger", d: "Displays invoice, payment, and return values per supplier" },
    "Rincian Buku Besar Pembantu Utang": { t: "Payables Subsidiary Ledger Detail", d: "Displays detailed invoice, payment, and return transactions per supplier" },
    "Grafik Umur Utang": { t: "Payables Aging Chart", d: "Displays a chart of unpaid supplier payables aging" },
    "Pernyataan Utang": { t: "Payables Statement", d: "Displays detailed payable statements to suppliers" },
    "Pembayaran Faktur": { t: "Invoice Payments", d: "Displays the list of invoice payments" },
    "Pembayaran PPh Pembelian": { t: "Purchase Income Tax Payments", d: "Displays payments for self-withheld purchase income tax" },
    "Pembayaran Pembelian": { t: "Purchase Payments", d: "Displays the list of payments to suppliers" },
    "Rincian Pembayaran Pembelian": { t: "Purchase Payment Details", d: "Displays detailed payment records to suppliers" },
    "Utang per Bulan": { t: "Payables per Month", d: "Report of suppliers with payable values per period within a year" },
    "Daftar Pemasok": { t: "Supplier List", d: "Report containing the list of suppliers" },
  },
  pembelian: {
    "Pembelian per Pemasok": { t: "Purchases per Supplier", d: "Displays purchase value list per supplier" },
    "Pembelian per Barang": { t: "Purchases per Item", d: "Displays purchase value list per item" },
    "Pembelian per Biaya": { t: "Purchases per Cost", d: "Displays purchase value list per cost" },
    "Rincian Pembelian per Pemasok": { t: "Purchase Details per Supplier", d: "Displays purchase value details per supplier" },
    "Rincian Pembelian per Barang": { t: "Purchase Details per Item", d: "Displays purchase value details per item" },
    "Histori Proses Pembelian": { t: "Purchase Process History", d: "Displays the purchase process chain from request to payment" },
    "Uang Muka Pembelian": { t: "Purchase Down Payments", d: "Displays purchase down payments grouped per supplier" },
    "Retur Pembelian per Barang": { t: "Purchase Returns per Item", d: "Displays return values per item" },
    "Pesanan per Pemasok (Belum Proses)": { t: "Orders per Supplier (Unprocessed)", d: "Displays unprocessed purchase order values per supplier" },
    "Pesanan per Barang (Belum Proses)": { t: "Orders per Item (Unprocessed)", d: "Displays unprocessed purchase order values per item" },
    "Daftar Pesanan Pembelian": { t: "Purchase Order List", d: "Report containing the list of purchase orders" },
    "Rincian Pesanan Pembelian": { t: "Purchase Order Details", d: "Report containing item details on purchase orders" },
    "Daftar Penerimaan Barang": { t: "Goods Receipt List", d: "Report containing the list of goods receipts" },
    "Rincian Penerimaan Barang": { t: "Goods Receipt Details", d: "Report containing item details on goods receipts" },
    "Daftar Faktur Pembelian": { t: "Purchase Invoice List", d: "Report containing the list of purchase invoices" },
    "Rincian Faktur Pembelian": { t: "Purchase Invoice Details", d: "Report containing item details on purchase invoices" },
    "Daftar Retur Pembelian": { t: "Purchase Return List", d: "Report containing the list of purchase returns" },
    "Rincian Retur Pembelian": { t: "Purchase Return Details", d: "Report containing item details on purchase returns" },
  },
  persediaan: {
    "Nilai Persediaan": { t: "Inventory Value", d: "Report of stock value and item cost changes within a selected period" },
    "Rincian Nilai Persediaan": { t: "Inventory Value Details", d: "Report of detailed stock value and cost change transactions" },
    "Rincian Nilai Persediaan (CSV)": { t: "Inventory Value Details (CSV)", d: "Download CSV of stock value and cost change transactions" },
    "Ketersediaan Stok Penjualan": { t: "Sales Stock Availability", d: "Report of item quantities available for sale" },
    "Rincian Ketersediaan Stok Penjualan": { t: "Sales Stock Availability Details", d: "Report of detailed stock available for sale" },
    "Umur Persediaan": { t: "Inventory Aging", d: "Report containing the list of stock aging" },
    "Rincian Umur Persediaan": { t: "Inventory Aging Details", d: "Report of detailed stock aging" },
    "Kartu Stok Persediaan": { t: "Inventory Stock Card", d: "Report of incoming and outgoing stock history details" },
    "Permintaan per Barang (Belum Proses)": { t: "Requests per Item (Unprocessed)", d: "Displays unprocessed item values per item" },
    "Daftar Permintaan Barang": { t: "Goods Request List", d: "Report containing the list of goods requests" },
    "Rincian Permintaan Barang": { t: "Goods Request Details", d: "Report of item details on goods requests" },
    "Status Pesanan Permintaan Barang": { t: "Goods Request Order Status", d: "Report of order status and order value for items on requests" },
    "Barang Grup": { t: "Group Items", d: "Displays item details of group-type items" },
    "Penyesuaian Stok Barang": { t: "Stock Adjustments", d: "Displays detailed stock adjustment data" },
    "Daftar Barang dan Jasa": { t: "Items & Services List", d: "Report containing the list of items and services" },
    "Umur Nomor Seri/Batch": { t: "Serial/Batch Number Aging", d: "Displays the aging of serial/batch numbers from stock" },
  },
  gudang: {
    "Kuantitas Barang per Gudang": { t: "Item Quantities per Warehouse", d: "Displays stock quantities per warehouse" },
    "Mutasi per Gudang": { t: "Mutations per Warehouse", d: "Displays incoming and outgoing stock mutation details per warehouse" },
    "Mutasi per Barang": { t: "Mutations per Item", d: "Displays incoming and outgoing mutation details per item" },
    "Ringkasan Mutasi Gudang": { t: "Warehouse Mutation Summary", d: "Displays incoming and outgoing stock mutation summary per warehouse" },
    "Stok Nomor Seri/Produksi": { t: "Serial/Production Number Stock", d: "Displays the list of item serial/production numbers" },
    "Stok Nomor Seri/Produksi per Barang": { t: "Serial/Production Stock per Item", d: "Displays serial/production numbers per item per warehouse" },
    "Stok Nomor Seri/Produksi per Gudang": { t: "Serial/Production Stock per Warehouse", d: "Displays serial/production numbers per warehouse per item" },
    "Histori Nomor Seri/Produksi": { t: "Serial/Production Number History", d: "Displays serial/production number mutation history" },
    "Mutasi Nomor Seri/Produksi": { t: "Serial/Production Number Mutations", d: "Displays incoming and outgoing serial/production number mutations" },
    "Nomor Produksi Segera Kadaluarsa": { t: "Production Numbers Expiring Soon", d: "Displays serial/production numbers that will soon expire" },
    "Sisa Umur per Nomor Produksi": { t: "Remaining Life per Production Number", d: "Displays remaining life data of item production numbers" },
    "Lembar Penghitungan Stok": { t: "Stock Count Sheet", d: "Displays the stock counting sheet" },
    "Barang Diterima Sebagian": { t: "Partially Received Items", d: "Report of inter-warehouse transfers where items are partially received" },
    "Rincian Pemindahan Barang": { t: "Stock Transfer Details", d: "Report of inter-warehouse stock transfers" },
    "Ringkasan Pemindahan Barang": { t: "Stock Transfer Summary", d: "Stock transfer summary" },
    "Daftar Gudang": { t: "Warehouse List", d: "Report containing the list of warehouses" },
  },
  "pekerjaan-pesanan": {
    "Bahan dan Biaya Pekerjaan per Bulan": { t: "Monthly Job Materials & Costs", d: "Report of job order materials and costs per month" },
    "Penyelesaian Barang/Biaya per Bulan": { t: "Monthly Item/Cost Completion", d: "Report of job order item and cost completion" },
    "Histori Pekerjaan Pesanan": { t: "Job Order History", d: "Job order history report" },
    "Rincian Jurnal Pekerjaan Pesanan": { t: "Job Order Journal Details", d: "Report of journal details from job orders" },
    "Rincian Penambahan Bahan Baku": { t: "Raw Material Addition Details", d: "Displays raw material addition details from job orders" },
    "Daftar Penambahan Bahan Baku": { t: "Raw Material Addition List", d: "Report containing the list of raw material additions" },
    "Rincian Akun Penyelesaian Pesanan": { t: "Order Completion Account Details", d: "Report of account details on order completions" },
    "Rincian Barang Penyelesaian Pesanan": { t: "Order Completion Item Details", d: "Report of item details on order completions" },
    "Daftar Penyelesaian Pesanan": { t: "Order Completion List", d: "Report containing the list of order completions" },
    "Daftar Pekerjaan Pesanan": { t: "Job Order List", d: "Report containing the list of job orders" },
  },
  manufaktur: {
    "Jurnal Perintah Kerja": { t: "Work Order Journal", d: "Displays journal history of the selected work order" },
    "Penyesuaian Bahan (Harga Pokok Produksi)": { t: "Material Adjustments (Cost of Goods)", d: "Report of raw material adjustment values as detail of material adjustment in COGS report" },
    "Pembelian (Harga Pokok Produksi)": { t: "Purchases (Cost of Goods)", d: "Report of raw material purchase values as detail of material purchases in COGS report" },
  },
  "aset-tetap": {
    "Daftar Aset Tetap": { t: "Fixed Asset List", d: "Report containing the list of fixed assets" },
    "Aset Tetap per Kategori": { t: "Fixed Assets per Category", d: "Report of fixed assets grouped by asset category" },
    "Detail Aset Tetap": { t: "Fixed Asset Details", d: "Report containing fixed asset details" },
    "Histori Aset": { t: "Asset History", d: "Displays asset value, depreciation, expense, book value, and profit/loss" },
    "Histori Lokasi Aset": { t: "Asset Location History", d: "Displays asset location change history" },
    "Histori Perubahan Aset": { t: "Asset Change History", d: "Displays all changes made to assets" },
    "Jurnal Aset": { t: "Asset Journal", d: "Displays journal history of the selected asset" },
    "Perbedaan Penyusutan": { t: "Depreciation Difference", d: "Report of the difference between accounting and tax depreciation" },
    "Daftar Perubahan Aset Tetap": { t: "Fixed Asset Change List", d: "Report containing the list of fixed asset changes" },
    "Daftar Disposisi Aset Tetap": { t: "Fixed Asset Disposal List", d: "Report containing the list of fixed asset disposals" },
    "Daftar Kategori Aset Tetap Pajak": { t: "Tax Fixed Asset Category List", d: "Report containing the list of tax fixed asset categories" },
  },
  pajak: {
    "Daftar PPN/PPnBM Keluaran": { t: "Output VAT/PPnBM List", d: "Displays output tax value details" },
    "Daftar PPN/PPnBM Masukan": { t: "Input VAT/PPnBM List", d: "Displays input tax value details" },
    "Rekonsiliasi PPN Lebih/Kurang Bayar": { t: "VAT Over/Underpayment Reconciliation", d: "Displays the difference between input tax and output tax" },
    "Faktur Penjualan SPT Masa PPN": { t: "Sales Invoices in Monthly VAT Return", d: "Report of sales invoices recorded in the VAT/PPnBM tax return" },
    "Faktur Pembelian SPT Masa PPN": { t: "Purchase Invoices in Monthly VAT Return", d: "Report of purchase invoices recorded in the VAT/PPnBM tax return" },
    "Daftar Bukti Potong PPh Penjualan": { t: "Sales Income Tax Withholding List", d: "Displays the list of income tax withholding proof for sales receipts" },
    "Daftar Bukti Potong PPh Pembelian": { t: "Purchase Income Tax Withholding List", d: "Displays the list of income tax withholding proof for purchase payments" },
  },
  pemeriksaan: {
    "Selisih Saldo Akun Persediaan dengan Nilai Barang": { t: "Inventory Account vs. Item Value Difference", d: "Displays the value difference between the inventory account and item values" },
    "Perbedaan Persediaan Terkirim Pemindahan Barang": { t: "Shipped Inventory Transfer Difference", d: "Displays processed stock transfers whose shipped inventory account journal differs" },
    "Laporan Rincian Penyetuju Transaksi": { t: "Transaction Approver Details", d: "Displays the approver report for every transaction" },
    "Selisih Akun Pembelian Belum Tertagih": { t: "Unpaid Purchase Account Difference", d: "Displays the details of unpaid purchase values" },
  },
  "lain-lain": {
    "Daftar FOB": { t: "FOB List", d: "Report containing the list of FOB" },
    "Daftar Pajak": { t: "Tax List", d: "Report containing the list of taxes" },
    "Daftar Pengiriman": { t: "Delivery Type List", d: "Report containing the list of delivery types" },
    "Daftar Karyawan": { t: "Employee List", d: "Report containing the list of employees" },
    "Daftar Log Aktifitas": { t: "Activity Log List", d: "Report containing the list of activity logs" },
    "Daftar Pengguna per Cabang": { t: "Users per Branch", d: "Report containing the list of users per branch" },
  },
}
