"use client"

import { getJournalLinesBySource, type JournalLine } from "@/lib/accounting-dummy-data"

/* ── Shared inline styles (matches accounting module convention) ── */
const thStyle: React.CSSProperties = {
  padding: "8px 12px", textAlign: "left", fontSize: 11, fontWeight: 600,
  color: "#444746", textTransform: "uppercase", letterSpacing: "0.04em",
  background: "#f8f9fa", borderBottom: "1px solid #e0e0e0", whiteSpace: "nowrap",
}
const thRight: React.CSSProperties = { ...thStyle, textAlign: "right" }
const fmt = (n: number) => n > 0 ? `Rp ${n.toLocaleString("id-ID")}` : "-"

interface JournalDetailPanelProps {
  /** Source transaction id (e.g. "so-1", "pay-2", "jrn-3") */
  sourceId: string
  /** Optional title override */
  title?: string
}

/**
 * Reusable "Rincian Jurnal" panel — shows the debit/credit journal lines
 * generated by a source transaction. Drop it into any accounting detail view.
 */
export function JournalDetailPanel({ sourceId, title = "Rincian Jurnal" }: JournalDetailPanelProps) {
  const journal: JournalLine | undefined = getJournalLinesBySource(sourceId)

  if (!journal) {
    return (
      <div style={{ border: "1px solid #e0e0e0", borderRadius: 8, padding: "16px 20px", background: "#fafafa" }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: "#001526", marginBottom: 8 }}>{title}</div>
        <p style={{ fontSize: 13, color: "#888", margin: 0 }}>Belum ada jurnal terkait transaksi ini.</p>
      </div>
    )
  }

  const totalDebit = journal.lines.reduce((s, l) => s + l.debit, 0)
  const totalKredit = journal.lines.reduce((s, l) => s + l.kredit, 0)
  const balanced = totalDebit === totalKredit

  return (
    <div style={{ border: "1px solid #e0e0e0", borderRadius: 8, overflow: "hidden", background: "#fff" }}>
      {/* Header */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 16px", background: "#f8f9fa", borderBottom: "1px solid #e0e0e0" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#0176d3" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" /><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z" />
          </svg>
          <span style={{ fontSize: 13, fontWeight: 600, color: "#001526" }}>{title}</span>
          <span style={{ fontSize: 11, color: "#888", fontFamily: "monospace" }}>{journal.sourceNo}</span>
        </div>
        <span style={{
          fontSize: 10, fontWeight: 600, padding: "2px 8px", borderRadius: 10,
          background: balanced ? "#e6f7e6" : "#fff3e0",
          color: balanced ? "#1a7a1a" : "#c77700",
        }}>
          {balanced ? "BALANCE" : "UNBALANCED"}
        </span>
      </div>

      {/* Meta row */}
      <div style={{ display: "flex", gap: 24, padding: "8px 16px", borderBottom: "1px solid #f0f0f0", fontSize: 12, color: "#444746" }}>
        <span>Tanggal: <b>{journal.tanggal}</b></span>
        <span>Tipe: <b>{journal.sourceType}</b></span>
        <span style={{ flex: 1, textAlign: "right", color: "#666" }}>{journal.keterangan}</span>
      </div>

      {/* Journal lines table */}
      <table style={{ width: "100%", borderCollapse: "collapse" }}>
        <thead>
          <tr>
            <th style={{ ...thStyle, width: 100 }}>No. Akun</th>
            <th style={thStyle}>Nama Akun</th>
            <th style={{ ...thRight, width: 140 }}>Debit</th>
            <th style={{ ...thRight, width: 140 }}>Kredit</th>
          </tr>
        </thead>
        <tbody>
          {journal.lines.map((line, i) => (
            <tr key={i} style={{ borderBottom: "1px solid #f5f5f5" }}>
              <td style={{ padding: "7px 12px", fontSize: 13, fontFamily: "monospace", color: "#0176d3" }}>{line.akun}</td>
              <td style={{ padding: "7px 12px", fontSize: 13, color: "#001526", paddingLeft: line.kredit > 0 && line.debit === 0 ? 28 : 12 }}>
                {line.namaAkun}
              </td>
              <td style={{ padding: "7px 12px", fontSize: 13, fontFamily: "monospace", textAlign: "right", color: "#001526" }}>{fmt(line.debit)}</td>
              <td style={{ padding: "7px 12px", fontSize: 13, fontFamily: "monospace", textAlign: "right", color: "#001526" }}>{fmt(line.kredit)}</td>
            </tr>
          ))}
        </tbody>
        <tfoot>
          <tr style={{ background: "#f8f9fa", borderTop: "2px solid #e0e0e0" }}>
            <td colSpan={2} style={{ padding: "8px 12px", fontSize: 12, fontWeight: 700, color: "#444746" }}>TOTAL</td>
            <td style={{ padding: "8px 12px", fontSize: 13, fontWeight: 700, fontFamily: "monospace", textAlign: "right", color: "#001526" }}>{fmt(totalDebit)}</td>
            <td style={{ padding: "8px 12px", fontSize: 13, fontWeight: 700, fontFamily: "monospace", textAlign: "right", color: "#001526" }}>{fmt(totalKredit)}</td>
          </tr>
        </tfoot>
      </table>
    </div>
  )
}
